name: 'Python单元测试'

on: 
  workflow_dispatch:

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - name: '使用自定义action进行单元测试'
      uses: 786980206/pytest@b398ba0882223a0490b3f6bafacbf0e68c975e27