name: 'Python单元测试'

on: 
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: '使用自定义action进行单元测试'
      uses: 786980206/pytest@main

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: '测试报告'        
    - name: '展示当前目录下文件'
      run: ls -la
