name: 'Python单元测试'

on: 
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: '使用自定义action进行单元测试'
      uses: 786980206/pytest@main

  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: 下载产物
      uses: actions/download-artifact@v3
      with:
        name: '测试报告'        
    - name: '展示当前目录下文件'
      run: ls -la

  set_output:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  get_output:
    runs-on: ubuntu-latest
    needs: set_output
    steps:
      - env:
          OUTPUT1: ${{needs.set_output.outputs.output1}}
          OUTPUT2: ${{needs.set_output.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
