name: 'Python单元测试'

on: 
  workflow_dispatch:

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - name: '代码下载'
      uses: actions/checkout@v3
      
    - name: 'python安装'
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        
    - name: '依赖库安装'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run unit tests
      run: pytest
