name: 'qml 构建'                                            # 等同于流水线名称

on:                                                              # 触发方式
  workflow_dispatch:

jobs:                                                            # 任务编排      
  l32:                                                           # Job ID
    runs-on: ubuntu-latest                                       # 指定执行环境
    steps:                                                       # 步骤编排
      - uses: actions/checkout@v3
        with:
          repository: zholos/qml
          submodules: true
      - run: |
          ./configure KXARCH=l32 CFLAGS="-m32 -O3"
          make
          make test    
          ls -l
      - uses: actions/upload-artifact@v3
        with:
          name: 'qx-x86.so'
          path: qx.so
